spblog/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/about'
  get 'pages/directions'
  resources :articles do
    resources :comments
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

spblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

spblog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy
  validates :title, presence: true, length: { maximum: 50 }
  validates :post, presence: true
end

spblog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

spblog/app/models/user.rb
class User < ApplicationRecord
  has_many :articles 
  validates :password, presence: true, length: { minimum: 8 }
  validates :email, presence: true
end

spblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

spblog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :post, :user_id)
    end
end

spblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])

    @comment = @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private 
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

spblog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def directions
  end
end

spblog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:password, :email)
    end
end

spblog/app/helpers/application_helper.rb
module ApplicationHelper
  def get_seasons()
    time = Time.new

    if(time.month >= 3) && (time.month <= 5)
      "Yeah it is Spring"
    elsif(time.month > 5) && (time.month <= 8)
      "Everyone Loves Summer"
    elsif(time.month > 8) && (time.month <= 10)
      "Put onm Your Coat because Fall is here"
    else
      "Yuck Winter"
    end
  end

  def get_random_number(max_value = 10)
    rand(max_value)
  end

  def get_random_welcome()
    opening = ["What a beautiful day.", "Welcome to our site.", "Thank you for stopping by."]
    middle = ["We hope you find what you need.", "We have a wide selection.", "Check out our sale items."]
    ending = ["Contact us if you need help.", "We are here to serve you.", "Call us if you need to 555-555-5555."]

    "#{opening[rand(3)]} #{middle[rand(3)]} #{ending[rand(3)]}"
  end
  
  def count_to_10
    x = 2
    number_list = '1'

    loop do
      number_list = number_list + ", " + x.to_s
      x += 1
      break if x > 10
    end
    "#{number_list}"
  end
end

spblog/app/helpers/articles_helper.rb
module ArticlesHelper
end

spblog/app/helpers/comments_helper.rb
module CommentsHelper
end

spblog/app/helpers/pages_helper.rb
module PagesHelper
end

spblog/app/helpers/users_helper.rb
module UsersHelper
end

spblog/app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_area :post %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

spblog/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

spblog/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr class="<%=  cycle('list_line_odd', 'list_line_even')%>">
        <td><%= article.title %></td>
        <td><%= article.post %></td>
        <td><%= article.user_id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

spblog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

spblog/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @article.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>

<h2>Comments</h2>

<% @article.comments.each do |comment| %>

  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

<% end %>

<h2>Add a Comment:</h2>

<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %> <br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

spblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header>
      <%= link_to image_tag("logo.svg", alt: "My Logo"), {:controller => 'pages', :action => 'home'}, {:class => 'websiteLogo'} %>
      <%= link_to "READIT", {:controller => 'pages', :action => 'home'}, {:class => 'websiteTitle'} %>
      </header>
      <nav id="horzNav">
        <p>
          <%= link_to 'Home', {:controller => 'pages', :action => 'home'} %>
          <%= link_to 'About', {:controller => 'pages', :action => 'about'} %>
          <%= link_to 'Directions', {:controller => 'pages', :action => 'directions'} %>
          <%= link_to 'Articles', {:controller => 'articles', :action => 'index'} %>
          <%= link_to 'Users', {:controller => 'users', :action => 'index'} %>
        </p>
      </nav>

      <main id="content">
      <%= yield %>
      </main>
    </div> <!-- END OF WRAPPER -->
  </body>
</html>

spblog/app/views/pages/about.html.erb
<% provide(:title, "About Us") %>
<h1>About Us</h1>
<p>We do what we love and love what we do!</p>
<p><a href="mailto:sean.pheneger.dev@gmail.com">Contact Sean for help</a></p>

spblog/app/views/pages/directions.html.erb
<% provide(:title, "Directions") %>
<h1>Directions</h1>

spblog/app/views/pages/home.html.erb
<% provide(:title, "Welcome") %>
<h1>Home</h1>
<p>Welcome to the home page</p>
<p><%= get_seasons() %></p>
<p><%= get_random_number(1000) %></p>
<p><%= get_random_welcome() %></p>
<p><%= count_to_10() %></p>

spblog/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

spblog/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

spblog/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

spblog/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

spblog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>